# Generated by Django 4.0.5 on 2022-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(default='NA', max_length=50)),
                ('description', models.TextField(default='NA')),
                ('price', models.FloatField(default=0.0)),
                ('color', models.TextField(default='Na')),
                ('stock', models.BooleanField(default='NA')),
                ('image', models.FileField(default='NA', upload_to='upload')),
                ('size', models.FloatField(default='NA')),
                ('category', models.TextField(default='Cloth')),
                ('delivery', models.SmallIntegerField(default=5)),
            ],
        ),
    ]
